version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: testedb
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'basis'
    ports:
      - '3306:3306'
    volumes:
      - ./scriptsdb:/docker-entrypoint-initdb.d 